Repository rurema/doctree, pull requests merged in 2019-12, with the labels that each got.

#1075 Add RubyVM::MJIT and --mjit* options
  refm/api/src/_builtin.rd
  refm/api/src/_builtin/RubyVM__MJIT
  refm/doc/spec/rubycmd.rd
Labels: Ruby2.6.0

#1746 Add ndigits to `Numeric#floor`
  refm/api/src/_builtin/Numeric
Labels: Ruby2.4.0, Ruby2.5.0

#1412 Add ERB#result_with_hash since 2.5.0
  refm/api/src/erb.rd
Labels: Ruby2.5.0

#1502 Range#cover? の更新
  refm/api/src/_builtin/Range
Labels: Ruby2.6.0

#565 Add sample code of String#isjis
  refm/api/src/kconv.rd
Labels: pending
