Repository rurema/doctree, pull requests merged in 2019-01, with the labels that each got.

#1685 `OpenStruct#to_h` with block
  refm/api/src/ostruct.rd
Labels: Ruby2.6.0

#1683 Add `exception:` keyword argument to BigDecimal
  refm/api/src/bigdecimal/BigDecimal
Labels: Ruby2.6.0

#1686 BigDecimal deprecated
  refm/api/src/bigdecimal/BigDecimal
Labels: Ruby2.6.0, Ruby2.7.0

#1691 bigdecimalライブラリを更新
  refm/api/src/bigdecimal/BigDecimal
  refm/api/src/bigdecimal/math.rd
Labels: Ruby2.6.0

#1048 Add `KeyError.new` with receiver: and key: since 2.6.0
  refm/api/src/_builtin/KeyError
  refm/api/src/_builtin/NameError
  refm/api/src/_builtin/NoMethodError
Labels: Ruby2.6.0

#1703 Update help message of httpd
  refm/api/src/un.rd
Labels: Ruby2.5.0, Ruby2.6.0
