Repository rurema/doctree, pull requests merged in 2020-06, with the labels that each got.

#2254 Add Array#intersection since Ruby 2.7
  refm/api/src/_builtin/Array
  refm/api/src/set.rd
Labels: Ruby2.7.0

#2260 Add Array#minmax since Ruby 2.7
  refm/api/src/_builtin/Array
  refm/api/src/_builtin/Enumerable
Labels: Ruby2.7.0

#2262 Update Comparable#clamp document because it receives a range since 2.7
  refm/api/src/_builtin/Comparable
Labels: Ruby2.7.0

#2264 Add Enumerable#filter_map since Ruby 2.7
  refm/api/src/_builtin/Enumerable
Labels: Ruby2.7.0

#2265 Add Enumerable#tally since Ruby 2.7
  refm/api/src/_builtin/Enumerable
Labels: Ruby2.7.0

#2271 Add Enumerator::Lazy#eager since Ruby 2.7
  refm/api/src/_builtin/Enumerator__Lazy
Labels: Ruby2.7.0

#2273 Add Enumerator::Yielder documentation
  refm/api/src/_builtin.rd
  refm/api/src/_builtin/Enumerator
  refm/api/src/_builtin/Enumerator__Yielder
Labels: Ruby2.7.0

#1983 Add sample code of RakeFileUtils.verbose_flag=
  refm/api/src/rake/RakeFileUtils
Labels: feedback

#2263 Add Complex#<=> since Ruby 2.7
  refm/api/src/_builtin/Complex
Labels: Ruby2.7.0

#2270 Add Enumerator.produce since Ruby 2.7
  refm/api/src/_builtin/Enumerator
Labels: Ruby2.7.0

#2272 Add Enumerator::Chain document sicne Ruby 2.6.0
  refm/api/src/_builtin.rd
  refm/api/src/_builtin/Enumerable
  refm/api/src/_builtin/Enumerator
  refm/api/src/_builtin/Enumerator__Chain
Labels: Ruby2.6.0

#2277 Add Fiber#raise since Ruby 2.7.0
  refm/api/src/_builtin/Fiber
Labels: Ruby2.7.0

#2282 Add document for (Proc|Method)#(<<|>>) since Ruby 2.6
  refm/api/src/_builtin/Method
  refm/api/src/_builtin/Proc
Labels: Ruby2.6.0

#551 Add sample code of String#pathmap_explode
  refm/api/src/rake/core_ext
Labels: pending

#2286 Add UnboundMethod#bind_call since 2.7.0
  refm/api/src/_builtin/Method
  refm/api/src/_builtin/UnboundMethod
Labels: Ruby2.7.0
