Repository rurema/doctree, pull requests merged in 2021-01, with the labels that each got.

#2417 Add NoMatchingPatternError since 2.7.0
  refm/api/src/_builtin.rd
  refm/api/src/_builtin/NoMatchingPatternError
Labels: Ruby2.7.0, Ruby3.0

#2429 Add Symbol#name since 3.0
  refm/api/src/_builtin/Symbol
Labels: Ruby3.0

#2431 Warning[:deprecated]がdeprecate_constantに影響することを追加
  refm/api/src/_builtin/Module
Labels: Ruby2.7.0

#1039 String#each_line, #lines の chomp の説明修正
  refm/api/src/_builtin/String
Labels: feedback

#2438 Moved Fiber methods into core [Feature #17407]
  refm/api/src/LIBRARIES
  refm/api/src/_builtin/Fiber
  refm/api/src/_builtin/Fiber.alive_p
  refm/api/src/_builtin/Fiber.current
  refm/api/src/_builtin/Fiber.transfer
  refm/api/src/fiber.rd
Labels: Ruby3.1

#2369 Method#inspect の 2.7.0 対応と samplecode 化
  refm/api/src/_builtin/Method
Labels: Ruby2.7.0

#2424 Add news 3_0_0
  refm/doc/news/3_0_0.rd
  refm/doc/news/index.rd
Labels: Ruby3.0
