Repository rurema/doctree, pull requests merged in 2021-03, with the labels that each got.

#2399 Update set
  refm/api/src/set.rd
Labels: Ruby3.0

#2408 Add :connect_timeout to TCPSocket.new since 3.0
  refm/api/src/socket/TCPSocket
Labels: Ruby3.0

#2452 The Queue constructor takes an initial set of objects
  refm/api/src/thread/Queue
Labels: Ruby3.1

#2472 Remove profile since 2.7.0
  refm/api/src/LIBRARIES
  refm/api/src/profile.rd
  refm/api/src/profiler.rd
Labels: Ruby2.7.0

#2475 GC.auto_compact / GC.auto_compact= の説明を追加
  refm/api/src/_builtin/GC
Labels: Ruby3.0

#2478 Enumerator::Lazy#filter_map の説明を追加
  refm/api/src/_builtin/Enumerator__Lazy
Labels: Ruby2.7.0

#2485 File.dirname optional level [Feature #12194]
  refm/api/src/_builtin/File
Labels: Ruby3.1
